version: "3"

services:
  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 64.227.65.203:2181
      KAFKA_LISTENERS: INTERNAL_SASL_PLAINTEXT://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_SASL_PLAINTEXT://167.172.34.24:9092,SASL_PLAINTEXT://167.172.34.24:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SASL_PLAINTEXT
      KAFKA_AUTHENTICATION: KERBEROS
      KAFKA_KERBEROS_PUBLIC_URL: 161.35.154.207
      KAFKA_KERBEROS_REALM: KAFKA.SECURE
      KAFKA_KERBEROS_API_URL: "http://161.35.154.207:3000/get-keytab"
      KAFKA_KERBEROS_API_KAFKA_USERNAME: kafka/167.172.34.24
      KAFKA_KERBEROS_API_KAFKA_PASSWORD: kafkaPasswordTester
      KAFKA_KERBEROS_API_ZOOKEEPER_USERNAME: zookeeper/64.227.65.203
      KAFKA_KERBEROS_API_ZOOKEEPER_PASSWORD: zookeeperPasswordTester
      KAFKA_HEAP_OPTS: "-Xmx3G"
      KAFKA_ACL_ENABLE: "true"
      KAFKA_ACL_SUPER_USERS: User:kafka;User:admin
      KAFKA_ZOOKEEPER_SET_ACL: "true"