version: "3"

services:
  kafka:
    image: omvk97/kafkatest:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "165.22.197.23:2181,167.172.43.211:2181,64.225.77.80:2181"
      KAFKA_BROKER_ID: 1
