version: "3"

services:
  zoo:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1
      # ZOO_PORT: 2181

  kafka:
    image: omvk97/kafka
    container_name: kafka2
    ports:
      - 9094:9094
      - 9095:9095
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9094,SASL_PLAINTEXT://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9094,SASL_PLAINTEXT://192.168.1.107:9095
      KAFKA_SSL_SERVER_HOSTNAME: localhost
      KAFKA_CERTIFICATE_AUTHORITY_URL: ca:5000
      KAFKA_AUTHENTICATION: KERBEROS
      KERBEROS_PUBLIC_URL: 134.209.204.101
      KERBEROS_REALM: KAFKA.SECURE
      KERBEROS_PRINCIPAL: kafka/localhost@KAFKA.SECURE
      KERBEROS_ZOOKEEPER: "false"
      KAFKA_HEAP_OPTS: "-Xmx4G"
    volumes:
      - ./kafka.service.keytab:/sasl/kafka.service.keytab
    depends_on:
      - zoo
      - ca

  ca:
    image: omvk97/ca
    container_name: ca
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./cert-auth:/ssl/
  # zoonavigator:
  #   image: elkozmon/zoonavigator
  #   container_name: zoonavigator
  #   ports:
  #     - 9000:9000
  #   environment:
  #     API_HOST: localhost
  #     HTTP_PORT: 9000
