FROM ubuntu:18.04

ENV KAFKA_HOME=/opt/kafka

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-8-jre-headless && \
    apt-get install -y jq

COPY ./kafka_2.12-2.4.0.tar /opt/

# Install kafka
RUN cd /opt && \
    tar -xf kafka_2.12-2.4.0.tar && \
    mv kafka_2.12-2.4.0 kafka && \
    rm -rf /opt/*.tgz && \
    mkdir ${KAFKA_HOME}/data

# Setup necessary scripts 
COPY scripts /tmp/
RUN chmod +x /tmp/*.sh && \
    mv /tmp/*.sh /usr/bin && \
    rm -rf /tmp/*

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "healthcheck.sh" ]

CMD [ "start.sh" ]