version: "3"

services:
  zoo:
    image: cfei/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_ID: 1
      ZOO_PORT: 2181

  kafka:
    build: ./
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENERS: SSL://0.0.0.0:9092,EXTERNAL_SSL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9092,EXTERNAL_SSL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_TLS_SERVER_DNS_HOSTNAME: localhost
      KAFKA_TLS_CLIENT_AUTH: required
    depends_on:
      - zoo
      - ca

  ca:
    image: omvk97/ca
    container_name: ca
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./cert-auth:/ssl/
