version: "3"

services:
  kafka:
    image: cfei/kafka:2.0.0-beta
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,SASL_PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,SASL_PLAINTEXT://localhost:9093
      KAFKA_AUTHENTICATION: KERBEROS
      KERBEROS_PUBLIC_URL: 128.199.53.160
      KERBEROS_REALM: KAFKA.SECURE
      KAFKA_KERBEROS_PRINCIPAL: kafka/localhost@KAFKA.SECURE
      ZOOKEEPER_KERBEROS_PRINCIPAL: zookeeper/localhost@KAFKA.SECURE
      KAFKA_HEAP_OPTS: "-Xmx4G"
      KAFKA_ACL_ENABLE: "true"
      KAFKA_ACL_SUPER_USERS: User:kafka
      KAFKA_ZOOKEEPER_SET_ACL: "true"
    volumes:
      - ./kafka.service.keytab:/sasl/kafka.service.keytab
      - ./zookeeper.service.keytab:/sasl/zookeeper.service.keytab